name: flutter_pet
description: FlutterPet

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.0-116.0.dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # 去除网页URL中的“#”(hash) https://flutter.cn/docs/development/ui/navigation/url-strategies
  url_strategy: 0.2.0
  # 网络库 https://github.com/flutterchina/dio
  dio: ^4.0.1
  # Dart 常用工具类库 https://github.com/Sky24n/common_utils
  common_utils: 2.0.2
  # Flutter 常用工具类库 https://github.com/Sky24n/flustars
  flustars: ^2.0.1
  # Flutter 轮播图 https://github.com/lianyagang/flutter_swiper_null_safety
  flutter_swiper_null_safety: ^1.0.2  # flutter_swiper很久不维护，可以使用空安全版本：flutter_swiper_null_safety
  # 格式化String https://github.com/Naddiseo/dart-sprintf
  sprintf: ^6.0.0
  # 路由框架 https://github.com/theyakka/fluro
  fluro: ^2.0.3
  # 图片缓存 https://github.com/renefloor/flutter_cached_network_image
  cached_network_image: ^3.1.0+1
  # Toast插件 https://github.com/OpenFlutter/flutter_oktoast
  oktoast: ^3.1.5
  # 获取当前设备信息 https://github.com/fluttercommunity/plus_plugins/tree/main/packages/device_info_plus
  device_info_plus: 3.1.1
  # 改变桌面端窗口大小(MacOS/Linux/Windows) https://github.com/mix1009/desktop_window
  desktop_window: 0.4.0
  # https://github.com/ReactiveX/rxdart
  rxdart: ^0.27.2
  # 侧滑删除 https://github.com/letsar/flutter_slidable
  flutter_slidable: ^0.6.0
  decimal: 1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/state/